//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_for_you
{
    using System;
    using System.Collections.Generic;
    
    public partial class komponenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public komponenta()
        {
            this.narucuje = new HashSet<narucuje>();
        }
    
        public int IdKomponenta { get; set; }
        public string Naziv { get; set; }
        public string Proizvodac { get; set; }
        public string Tip { get; set; }
        public int Potrosnja { get; set; }
        public double Cijena { get; set; }
        public string Socket { get; set; }
        public string Tip_memorije { get; set; }
        public string Brzina { get; set; }
        public string Velicina_memorije { get; set; }
        public string Interface { get; set; }
        public Nullable<double> Duzina_graficke { get; set; }
        public string Vram { get; set; }
        public Nullable<int> Kapacitet_napajanja { get; set; }
        public Nullable<double> Maksimalna_duzina_graficke { get; set; }
        public string Podrzavana_maticna { get; set; }
        public string KapacitetPohrane { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narucuje> narucuje { get; set; }
    }
}
