//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_for_you
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnik()
        {
            this.narudzba = new HashSet<narudzba>();
        }
    
        public int IdKorisnik { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Ime_prezime { get; set; }
        public string Adresa { get; set; }
        public string E_mail { get; set; }
        public int Uloga { get; set; }
    
        public virtual uloga uloga1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzba> narudzba { get; set; }
    }
}
