//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_for_you
{
    using System;
    using System.Collections.Generic;
    
    public partial class maticna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maticna()
        {
            this.narucuje = new HashSet<narucuje>();
        }
    
        public int IdMaticne { get; set; }
        public string Naziv { get; set; }
        public string Proizvodac { get; set; }
        public int Potrosnja { get; set; }
        public double Cijena { get; set; }
        public string Socket { get; set; }
        public string Velicina { get; set; }
        public string Tip_memorije { get; set; }
        public int Broj_modula_za_memoriju { get; set; }
        public short InterfacePCIe8 { get; set; }
        public short InterfacePCIe16 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narucuje> narucuje { get; set; }
    }
}
