//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_for_you
{
    using System;
    using System.Collections.Generic;
    
    public partial class narucuje
    {
        public int IdNarucuje { get; set; }
        public int IdNarudzbe { get; set; }
        public Nullable<int> IdKomponente { get; set; }
        public Nullable<int> IdMaticne { get; set; }
        public int Kolicina { get; set; }
    
        public virtual komponenta komponenta { get; set; }
        public virtual maticna maticna { get; set; }
        public virtual narudzba narudzba { get; set; }
    }
}
