//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_for_you
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public narudzba()
        {
            this.narucuje = new HashSet<narucuje>();
        }
    
        public int IdNarudzba { get; set; }
        public int IdKorisnika { get; set; }
        public System.DateTime Datum { get; set; }
        public double Ukupna_cijena { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narucuje> narucuje { get; set; }
    }
}
